--
--  Luacheck.lua - include file auto-generated by toybox.py (https://toyboxpy.io).
--

local toyboxes = {}
toyboxes.read_globals = {}

local function luacheckMerge(other)
    if other.globals ~= nil then
        for k, v in pairs(other.globals) do
            toyboxes.read_globals[k] = v
        end
    end

    if other.read_globals ~= nil then
        for k, v in pairs(other.read_globals) do
            toyboxes.read_globals[k] = v
        end
    end
end

-- Add globals from the toyboxes as read-only globals.
luacheckMerge(require "toyboxes/github-dot-com/DidierMalenfant/Plupdate/luacheck/Luacheck")
luacheckMerge(require "toyboxes/github-dot-com/DidierMalenfant/pdbase/luacheck/Luacheck")
luacheckMerge(require "toyboxes/github-dot-com/DidierMalenfant/TiledUp/luacheck/Luacheck")
luacheckMerge(require "toyboxes/github-dot-com/DidierMalenfant/FontSample/luacheck/Luacheck")
luacheckMerge(require "toyboxes/github-dot-com/DidierMalenfant/Aspen/luacheck/Luacheck")

return function(stds, files)
    stds.toyboxes = toyboxes

    -- Also add globals for files from the toyboxes themselves as the project intended.
    stds.toybox_1 = require "toyboxes/github-dot-com/DidierMalenfant/Plupdate/luacheck/Luacheck"
    files["toyboxes/github-dot-com/DidierMalenfant/Plupdate"].std="+toybox_1"

    stds.toybox_2 = require "toyboxes/github-dot-com/DidierMalenfant/pdbase/luacheck/Luacheck"
    files["toyboxes/github-dot-com/DidierMalenfant/pdbase"].std="+toybox_2"

    stds.toybox_3 = require "toyboxes/github-dot-com/DidierMalenfant/TiledUp/luacheck/Luacheck"
    files["toyboxes/github-dot-com/DidierMalenfant/TiledUp"].std="+toybox_3"

    stds.toybox_4 = require "toyboxes/github-dot-com/DidierMalenfant/FontSample/luacheck/Luacheck"
    files["toyboxes/github-dot-com/DidierMalenfant/FontSample"].std="+toybox_4"

    stds.toybox_5 = require "toyboxes/github-dot-com/DidierMalenfant/Aspen/luacheck/Luacheck"
    files["toyboxes/github-dot-com/DidierMalenfant/Aspen"].std="+toybox_5"
end
