//
//  toyboxes.h - include file auto-generated by toybox.py (https://toyboxpy.io).
//

#include "github-dot-com/DidierMalenfant/pdbase/pdbase/pdbase.h"

#define REGISTER_TOYBOXES(pd)   register_pdbase(pd);
