--
--  toyboxes.lua - include file auto-generated by toybox.py (https://toyboxpy.io).
--

import 'github-dot-com/DidierMalenfant/Plupdate/Plupdate.lua'
import 'github-dot-com/DidierMalenfant/pdbase/pdbase.lua'
import 'github-dot-com/DidierMalenfant/TiledUp/source/TiledUp.lua'
import 'github-dot-com/DidierMalenfant/FontSample/FontSample.lua'
import 'github-dot-com/Whitebrim/AnimatedSprite/AnimatedSprite.lua'
import 'github-dot-com/DidierMalenfant/Aspen/source/Aspen.lua'
